GET http://localhost:3001/api/headers
Accept: application/json

###

GET http://localhost:3001/api/sections
Accept: application/json

###

GET http://localhost:3001/api/footers
Accept: application/json

###

GET http://localhost:3001/api/webconfig
Accept: application/json

###

POST http://localhost:3001/api/edit?type=header&comp=standard.gohtml

###

POST http://localhost:3001/api/editoptions?type=header
Content-Type: application/json

{
  "Color": "#ffffff",
  "BackColor": "#8000ff"
}
